language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "10"
  - "8"
  - "8.10"

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6.4.1; fi

script:
   - grunt standards
